### ISSUE TITLE
Expo start gives a error

### ISSUE THREAD

**Issue by jsiddharth** [xinthink/react-native-material-kit#444]
22:50
Error: Cannot resolve entry file: The `main` field defined in your `package.json` points to a non-existent path.
    at getEntryPointWithExtensions (/usr/lib/node_modules/expo-cli/node_modules/@expo/config/src/paths/paths.ts:73:17)
    at Object.getEntryPoint (/usr/lib/node_modules/expo-cli/node_modules/@expo/config/src/paths/paths.ts:32:10)
    at Object.resolveEntryPoint (/usr/lib/node_modules/expo-cli/node_modules/xdl/src/tools/resolveEntryPoint.ts:21:17)
    at getManifestResponseAsync (/usr/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:198:22)
    at getManifestResponseFromHeadersAsync (/usr/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:177:10)
    at /usr/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:137:55
    at call (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at /home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:803:9
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:99:24)
    at _next (/home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:119:9)
    at /home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:124:7
    at new Promise (<anonymous>)
    at /home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:116:12
    at Server._processRequest (/home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:805:7)
    at /home/yogesh/mCruiseOn/badass/react-native-material-kit/node_modules/metro/src/Server.js:209:12
    at call (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at next (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:161:14)
    at jsonParser (/usr/lib/node_modules/expo-cli/node_modules/@expo/dev-server/node_modules/body-parser/lib/types/json.js:110:7)
    at call (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at SendStream.error (/usr/lib/node_modules/expo-cli/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:365:28)
    at SendStream.emit (node:domain:470:12)
    at SendStream.error (/usr/lib/node_modules/expo-cli/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/usr/lib/node_modules/expo-cli/node_modules/send/index.js:421:12)
    at next (/usr/lib/node_modules/expo-cli/node_modules/send/index.js:764:28)
    at /usr/lib/node_modules/expo-cli/node_modules/send/index.js:772:23
    at FSReqCallback.oncomplete (node:fs:194:21)

**Comment by jsiddharth** [comment]
package.json has
{
  "name": "react-native-material-kit",
  "version": "0.6.0-beta.2",
  "description": "Bringing Material Design to React Native",
  "main": "lib/index.js",
  "typings": "lib/react-native-material-kit.d.ts",
  "author": "Yingxin Wu <yingxinwu.g@gmail.com>",
  "contributors": [
    "Quentin Valmori (https://github.com/Crash--)",
    "Alexander Price (https://github.com/alexprice91)"
  ],

There is no lib folder in the project
